### ISSUE TITLE
Specialization of Artist

### ISSUE THREAD

**Issue by atamboli4718** [ABooth9422/Project1#8]
### User Story

As a user I would like to find an artist specializing in the subject and style of tattoo I’m looking for.

### Acceptance Criteria
When selecting an artist based on style, include:
- [ ] image examples for the different styles and subject matter of tattoos
- [ ] allow the user to select one style or "any"
- [ ] save user input for future db call

**Comment by ABooth9422** [comment]
went a different direction >.<
